export const SITE = {
  name: 'CVFlow',
  tagline: 'Analysez vos CV avec l\'IA en un instant',
  description: 'CVFlow analyse et optimise vos CV grâce à l\'intelligence artificielle. Connectez votre propre clé API et obtenez des retours détaillés en streaming.',
  url: 'https://example.com',
  ctaPrimary: 'Lancer l\'analyse',
  ctaSecondary: 'Voir comment ça marche',
  nav: [
    { label: 'Fonctionnalités', href: '#features' },
    { label: 'Comment ça marche', href: '#how-it-works' },
    { label: 'FAQ', href: '#faq' },
  ],
  hero: {
    eyebrow: 'ANALYSE IA DE CV',
    badge: 'NOUVEAU',
    headline: ['Analysez vos CV', 'avec l\'IA en streaming.'],
    highlight: 'IA',
    sub: 'Les recruteurs passent 6 secondes sur un CV. Notre IA détecte chaque point faible et vous guide vers un CV qui retient l\'attention.',
    emphasis: 'Résultats en temps réel, directement dans votre navigateur.',
    micro: 'Gratuit · Sans inscription · Vos données restent locales',
  },
  stats: [
    { value: 6, suffix: 's', label: 'Temps moyen de scan recruteur' },
    { value: 50, suffix: '+', label: 'Critères analysés par CV' },
    { value: 3, suffix: '', label: 'Modèles IA supportés' },
    { value: 100, suffix: '%', label: 'Stockage côté navigateur' },
  ],
  steps: [
    { step: '01', title: 'Connectez votre clé API', description: 'Choisissez Gemini, Claude ou OpenAI. Votre clé reste dans votre navigateur, jamais sur nos serveurs.' },
    { step: '02', title: 'Déposez votre CV', description: 'Collez le texte ou importez un fichier. L\'analyse démarre instantanément.' },
    { step: '03', title: 'Recevez votre analyse', description: 'Score global, points forts, axes d\'amélioration et suggestions concrètes, le tout en streaming.' },
  ],
  features: [
    {
      icon: 'FileCheck' as const,
      color: 'brand-green' as const,
      title: 'Analyse complète',
      description: 'Détection des points forts et axes d\'amélioration sur plus de 50 critères.',
      visual: 'pills' as const,
    },
    {
      icon: 'Gauge' as const,
      color: 'brand-blue' as const,
      title: 'Score détaillé',
      description: 'Score global et sous-scores par catégorie avec visualisation en temps réel.',
      visual: 'score' as const,
    },
    {
      icon: 'PenLine' as const,
      color: 'brand-red' as const,
      title: 'Suggestions de réécriture',
      description: 'Reformulations concrètes pour chaque section à améliorer.',
      visual: 'rewrite' as const,
    },
    {
      icon: 'Zap' as const,
      color: 'brand-amber' as const,
      title: 'Streaming en temps réel',
      description: 'Les résultats s\'affichent token par token, pas besoin d\'attendre la fin.',
      visual: 'console' as const,
    },
    {
      icon: 'BarChart3' as const,
      color: 'brand-cyan' as const,
      title: 'Comparaison sectorielle',
      description: 'Évaluez votre CV par rapport aux standards de votre secteur.',
      visual: 'bars' as const,
    },
    {
      icon: 'Lock' as const,
      color: 'brand-purple' as const,
      title: 'Clé API locale',
      description: 'Votre clé API ne quitte jamais votre navigateur. Aucun stockage serveur.',
      visual: 'key' as const,
    },
  ],
  testimonials: [
    { quote: 'Placeholder — L\'analyse a détecté des incohérences que je n\'avais pas vues après trois relectures.', name: 'A. Placeholder', role: 'Candidat placeholder', initials: 'AP' },
    { quote: 'Placeholder — Le streaming rend l\'attente agréable, on voit les résultats arriver en direct.', name: 'B. Placeholder', role: 'Recruteur placeholder', initials: 'BP' },
    { quote: 'Placeholder — J\'apprécie que ma clé API reste dans mon navigateur. Aucune donnée sur leurs serveurs.', name: 'C. Placeholder', role: 'Développeur placeholder', initials: 'CP' },
    { quote: 'Placeholder — En trois itérations, mon score est passé de 45 à 82. Les suggestions sont concrètes.', name: 'D. Placeholder', role: 'Designer placeholder', initials: 'DP' },
    { quote: 'Placeholder — L\'outil compare mon CV aux standards du secteur, c\'est exactement ce qu\'il me fallait.', name: 'E. Placeholder', role: 'Manager placeholder', initials: 'EP' },
    { quote: 'Placeholder — Interface claire, résultats pertinents. J\'ai recommandé CVFlow à toute mon équipe.', name: 'F. Placeholder', role: 'RH placeholder', initials: 'FP' },
    { quote: 'Placeholder — Le support multi-provider est un vrai plus, je peux comparer les retours entre modèles.', name: 'G. Placeholder', role: 'Consultant placeholder', initials: 'GP' },
    { quote: 'Placeholder — Gratuit et sans inscription, c\'est rare pour un outil de cette qualité.', name: 'H. Placeholder', role: 'Étudiant placeholder', initials: 'HP' },
  ],
  faq: [
    { q: 'Comment fonctionne le stockage de ma clé API ?', a: 'Votre clé API est stockée uniquement dans le localStorage de votre navigateur. Elle n\'est jamais envoyée à nos serveurs, jamais journalisée, jamais persistée côté backend. Elle transite uniquement via un header HTTP vers le proxy qui la transmet directement au fournisseur IA, puis l\'oublie.' },
    { q: 'Quels fournisseurs d\'IA sont supportés ?', a: 'CVFlow supporte Gemini (Google), Claude (Anthropic) et GPT (OpenAI). Vous pouvez basculer entre les trois à tout moment.' },
    { q: 'Mes données de CV sont-elles conservées ?', a: 'Non. Le texte de votre CV est envoyé directement au fournisseur IA via notre proxy. Rien n\'est stocké, journalisé ou conservé côté serveur.' },
    { q: 'L\'outil est-il vraiment gratuit ?', a: 'CVFlow est gratuit. Vous utilisez votre propre clé API, ce qui signifie que les coûts d\'utilisation de l\'IA sont ceux de votre compte chez le fournisseur choisi.' },
    { q: 'Puis-je utiliser l\'outil sans clé API ?', a: 'Une clé API est nécessaire pour l\'analyse IA. Chaque fournisseur propose un tier gratuit ou des crédits de démarrage suffisants pour tester.' },
  ],
  finalCta: {
    headline: ['Prêt à améliorer', 'votre CV ?'],
    sub: 'Connectez votre clé API et obtenez une analyse détaillée en quelques secondes.',
    micro: 'Gratuit · Sans inscription · Données locales',
  },
  footer: {
    blurb: 'CVFlow analyse vos CV avec l\'IA en streaming. Vos clés et données restent dans votre navigateur.',
    columns: [
      { title: 'Produit', links: [{ label: 'Application', href: '/app' }, { label: 'Fonctionnalités', href: '#features' }, { label: 'FAQ', href: '#faq' }] },
      { title: 'Ressources', links: [{ label: 'Comment ça marche', href: '#how-it-works' }, { label: 'Documentation', href: '#' }, { label: 'Contact', href: '#' }] },
    ],
    legal: '© 2026 CVFlow. Tous droits réservés.',
  },
} as const
